### ISSUE TITLE
Is it possible to get JSON output on return?

### ISSUE THREAD

**Issue by anuranBarman** [FurqanSoftware/node-whois#102]
Hi, I am using this module for some personal project. Is it possible to get the output as JSON. Currently it returns everything as String which is not parsable. I need to extract the ISP name and address. Is it possible?

**Comment by lancedolan** [comment]
https://www.npmjs.com/package/whois-json 
⬆️ a tiny npm package that just wraps `whois` and returns json.

**Comment by Batur123** [comment]
> https://www.npmjs.com/package/whois-json
> ⬆️ a tiny npm package that just wraps `whois` and returns json.

That package is not working properly at all. It sometimes returns the wrong json response.

**Comment by hjr265** [comment]
Closing this issue. Parsing the WHOIS data is not within the scope of this package.
