### ISSUE TITLE
Doesn't work with webpack

### ISSUE THREAD

**Issue by epicfaace** [FurqanSoftware/node-whois#108]
## Problem
I can't use whois when using webpack because of the shebang at the beginning of the compiled whois/index.js file.

![image](https://user-images.githubusercontent.com/1689183/119551970-33e7a680-bd68-11eb-9d8f-e15a2c4071d6.png)

I get the following error:

```
Entrypoint worker = worker.bundle.js
[0] ./src/worker.ts 116 bytes {0} [built]
    + 1 hidden module

ERROR in ./node_modules/whois/index.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
| 
| // Generated by CoffeeScript 2.5.1
 @ ./src/worker.ts 3:12-28
```

This is a similar issue to https://github.com/webpack/webpack/issues/2168

## Solution
The solution would be to remove the shebang from index.js and create a separate entry point, bin.js, which has the shebang and would be used for the CLI. See this commit to see how another library with a similar problem, JSONStream, did it: https://github.com/dominictarr/JSONStream/commit/debb492597e1332318798bdd9802f36c21034151

## Temporary workaround
A short-term workaround for our purposes was to install `string-replace-loader` and then add the following within our webpack config `rules` key:

```js
{
    test: path.resolve(__dirname, 'node_modules/whois/index.js'),
    loader: 'string-replace-loader',
    options: {
      search: '#!/usr/bin/env node',
      replace: ''
    }
}
```

**Comment by epicfaace** [comment]
Woah thanks for the fix @hjr265 ! That's awesome 😁

**Comment by hjr265** [comment]
@epicfaace No problem. Sorry I couldn't leave a note here earlier. I published the change and immediately had to switch to something else.
