### ISSUE TITLE
Error: "ENOTFOUND" for .io domain.

### ISSUE THREAD

**Issue by jatin-vl** [FurqanSoftware/node-whois#114]
Hi, I am facing an issue while trying to run a whois.lookup on the "example.com" domain from my node.js project. Getting the below error but when running "whois -h whois.nic.io example.com" command from the terminal, it is working as expected. Right now I am facing this issue only for a particular domain. 
Please replace domain(example.com) with "tamanu dot io" to reproduce an error.

{
  errno: -3008,
  code: "ENOTFOUND",
  syscall: "getaddrinfo",
  hostname: "www.ascio.com/products/availability-check/whois",
}
  message: "getaddrinfo ENOTFOUND www.ascio.com/products/availability-check/whois"
  Error: getaddrinfo ENOTFOUND www.ascio.com/products/availability-check/whois
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
    
 Note: I am using the host from servers.json file provided in the repository.
 
 Can you please help me to resolve this?
 
![image (1)](https://user-images.githubusercontent.com/93173725/157663069-4ef7fd07-2b92-4ab0-8291-616bbc3a5f65.png)

**Comment by jbuhacoff** [comment]
From your output:

```
{
errno: -3008,
code: "ENOTFOUND",
syscall: "getaddrinfo",
hostname: "www.ascio.com/products/availability-check/whois",
}
```

Notice the hostname value `www.ascio.com/products/availability-check/whois` is not a valid hostname, it's a hostname and a path like something that might be in a URL.

Have you tried it with just `www.ascio.com`?

This code works fine for me:

```
import whois from 'whois';
whois.lookup('www.ascio.com', {}, (err, data) => {
    if (err) { console.error('failed'); }
    if (data) { console.log(data); }
});
```

**Comment by RushdiGG** [comment]
Hi, I had the same issue, for me the solution was adding "www." to cleanParsingErrors:

cleanParsingErrors = (string) => {
    return string.replace(/^[:\s]+/, '').replace(/^https?[:\/]+/, '')**.replace(/^www\./, '')** || string;
  };

**Comment by chrsdbll** [comment]
> I got a similar issue from .io domains registered with GoDaddy.
> 
> Reproduced with a domain name that I own that has this issue:
> 
> ```
> import whois from 'whois';
> whois.lookup('libertydns.io', {}, (err, data) => {
>     if (err) { console.error(err); }
>     if (data) { console.info(data); }
> });
> ```
> 
> Output:
> 
> ```
> {
> errno: -3008,
> code: "ENOTFOUND",
> syscall: "getaddrinfo",
> hostname: "whois.godaddy.com/",
> }
> ```

I have experienced the same issue with .io domains. I did some tracing, and it turns out that the issue resides with the trailing / character at the end of the hostname for the registrar.

**Comment by umutm** [comment]
Yes, it seems to be due to the "/" suffix in hostname.

Updating the regex at index.js line: 109 as:

`match = data.replace(/\r|\//gm, '').match(/(ReferralServer|Registrar Whois|Whois Server|WHOIS Server|Registrar WHOIS Server):[^\S\n]*((?:r?whois|https?):\/\/)?(.*)/);`

fixes the issue.
