### ISSUE TITLE
make `--timeout` as a cli option

### ISSUE THREAD

**Issue by jerrygreen** [FurqanSoftware/node-whois#123]
Currently there's no such option.

![image](https://github.com/FurqanSoftware/node-whois/assets/13215662/160005ef-6c53-4419-82c7-6a7fac754ee6)

By the way, why the thing called bin.js not whois.js?

**Comment by hjr265** [comment]
@jerrygreen Thank you for reporting this!

New release has a fix for this: https://www.npmjs.com/package/whois v2.14.2
