### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by AngryElephant** [FurqanSoftware/node-whois#28]
Hi,

Is there any way to add proxy support ? I got ban for 30 minutes each 300 request (around).

Thanks.

**Comment by hjr265** [comment]
Hi @AngryElephant,

This sounds like an interesting requirement. I will look into this.

**Comment by liesislukas** [comment]
Any progress on this?

**Comment by hjr265** [comment]
Sorry I didn't quite get a chance to take care of this yet. I will try to do it soon. But if anyone wants to send a pull request, I will be happy to take a look at it.

**Comment by samhunta** [comment]
I'm working on this now 👍

**Comment by hjr265** [comment]
Thank you @samhunta for taking care of this.

**Comment by iggyZiggy** [comment]
any update about this?

**Comment by DannyCork** [comment]
so  needed :)

**Comment by hjr265** [comment]
This is done. However, please do share your feedback if you have any. 

Since this isn't something that we had originally planned for, we kept the changes as simple as possible for now.
