### ISSUE TITLE
Doesn't work with weird TLD's

### ISSUE THREAD

**Issue by stamsarger** [FurqanSoftware/node-whois#38]
I tried to use it on websites like cia.GOV, pcsteps.GR, etc. I guess it has an issue with TLDs. Can you fix it?

**Comment by hjr265** [comment]
For .gov, can you please specify what you expected to be returned by the WHOIS server, and what you saw instead?

For .gr, this is a bit odd but I can't seem to find the WHOIS server information for .gr TLD. I have this for now: https://grweb.ics.forth.gr/public/Whois?lang=en but that's behind a captcha and would require fundamental changes in the way the library works now.

**Comment by rotsee** [comment]
There does indeed not seem to exist any .gr whois service (https://www.iana.org/domains/root/db/gr.html), and to agreement to explain why (https://www.icann.org/resources/pages/cctlds/cctlds-en). This is not uncommon, but given that FORTH seem to be reporting to the Ministry for Education in Greece(?), you might be able to put some political pressure on them to provide this. Call your favourite MP, and explain why open whois servers are important to the general public!

**Comment by stamsarger** [comment]
I get it that .gr is hard to implement, I don't really get why but, who cares.
When it comes to .gov, it sends an [object Object] error:
![image](https://user-images.githubusercontent.com/13446658/27012242-f768d586-4ed4-11e7-93bd-e0e61135dc61.png)
That's what it shows in the console:
![image](https://user-images.githubusercontent.com/13446658/27012261-3719247e-4ed5-11e7-9784-138f1e858442.png)
By the way it works perfectly with .com and .net TLDs.
![image](https://user-images.githubusercontent.com/13446658/27012270-55e30d5c-4ed5-11e7-8e31-7a7119331639.png)

**Comment by hjr265** [comment]
Hi @stamsarger, I may be missing something, but from the stack trace it doesn't seem the error stems from this package.

**Comment by hjr265** [comment]
I am closing this issue for now. Please reopen if you feel this is still relevant.
