### ISSUE TITLE
Does bin file need a node shebang?

### ISSUE THREAD

**Issue by gitgrimbo** [FurqanSoftware/node-whois#39]
Does the 'bin' file that npm uses need a shebang?

`#!/usr/bin/env node`

I'm using `whois` on Windows and it's just opening the `index.js` file in a text editor, rather than executing it via node.  See http://stackoverflow.com/a/10398567/319878.

Sample `.cmd` file for Grunt, generated by npm:

```
type C:\Users\xxx\AppData\Roaming\npm\grunt.cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\grunt-cli\bin\grunt" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\grunt-cli\bin\grunt" %*
)
```

The `whois.cmd` file, generated by npm:

```
type C:\Users\xxx\AppData\Roaming\npm\whois.cmd
@"%~dp0\node_modules\whois\index.js"   %*
```

I've copied the scaffolding from the Grunt file and it works fine, but I think the shebang needs to be in the generated index.js (or other bin file) in order for npm to generate the correct `.cmd` file.

**Comment by MRokas** [comment]
It doesn't even find index.js for me -
`line 1: /node_modules/whois/index.js: No such file or directory`

:/

**Comment by hjr265** [comment]
I have changed the Makefile to prepend a shebang to index.js. However, I need to test this from a Windows device first. I can do that once I am back home today.

If it works there, I will publish a new version to NPM later today.

**Comment by hjr265** [comment]
@gitgrimbo I finally managed to test it on Windows. I am really sorry for the delay.

Just so you know the change was working since my last comment, I just couldn't verify it before.

**Comment by gitgrimbo** [comment]
No worries, thanks!
