### ISSUE TITLE
Add support for .ONLINE TLD

### ISSUE THREAD

**Issue by bershan2** [FurqanSoftware/node-whois#51]
Please augment `servers.json` with line 
```
  "online": "whois.centralnic.net",
```
to add support for .ONLINE TLD.

### Explanation of .ONLINE
Try searching for `example.online` using this:
```
var whois = require('whois');
whois.lookup('example.online', function(err, data){
    if (err) throw err;
    console.log(data);
});
```

<details><summary>Without the line you get error message</summary>
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

%ERROR:101: no entries found
%
% No entries found in source RIPE.

% This query was served by the RIPE Database Query Service version 1.89.2 (BLAARKOP)
</details>

<details><summary>With the line you get actual seac</summary>
Domain Name: EXAMPLE.ONLINE
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2017-10-15T22:33:31.0Z <<<

This domain is not available for registration. It has been reserved
in compliance with Specification 5 of the New gTLD Registry
Agreement. Please see https://gitlab.centralnic.com/centralnic/
spec5-reserved-names/blob/master/README.md for more information.

For more information on Whois status codes, please visit https://icann.org/epp

This whois service is provided by CentralNic Ltd and only contains
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd https://www.centralnic.com/

Access to the whois service is rate limited. For more information, please
see https://registrar-console.centralnic.com/pub/whois_guidance.
</details>

Note that `example.online` is a special domain, so its lookup result is a special message. Here is a lookup of my own domain `homograph.online`:
<details><summary>homograph.online lookup after the fix</summary>
Domain Name: HOMOGRAPH.ONLINE
Registry Domain ID: D53940563-CNIC
Registrar WHOIS Server: whois.namecheap.com
Registrar URL:
Updated Date: 2017-10-14T21:00:57.0Z
Creation Date: 2017-10-14T21:00:55.0Z
Registry Expiry Date: 2018-10-14T23:59:59.0Z
Registrar: Namecheap
Registrar IANA ID: 1068
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: addPeriod https://icann.org/epp#addPeriod
Registry Registrant ID: C153667758-CNIC
Registrant Name: WhoisGuard Protected
Registrant Organization: WhoisGuard, Inc.
Registrant Street: P.O. Box 0823-03411
Registrant City: Panama
Registrant State/Province: Panama
Registrant Postal Code:
Registrant Country: PA
Registrant Phone: +507.8365503
Registrant Fax: +51.17057182
Registrant Email: fa2174061cfe420dbee5a89e29053d94.protect@whoisguard.com
Registry Admin ID: C153667768-CNIC
Admin Name: WhoisGuard Protected
Admin Organization: WhoisGuard, Inc.
Admin Street: P.O. Box 0823-03411
Admin City: Panama
Admin State/Province: Panama
Admin Postal Code:
Admin Country: PA
Admin Phone: +507.8365503
Admin Fax: +51.17057182
Admin Email: fa2174061cfe420dbee5a89e29053d94.protect@whoisguard.com
Registry Tech ID: C153667763-CNIC
Tech Name: WhoisGuard Protected
Tech Organization: WhoisGuard, Inc.
Tech Street: P.O. Box 0823-03411
Tech City: Panama
Tech State/Province: Panama
Tech Postal Code:
Tech Country: PA
Tech Phone: +507.8365503
Tech Fax: +51.17057182
Tech Email: fa2174061cfe420dbee5a89e29053d94.protect@whoisguard.com
Name Server: DNS1.REGISTRAR-SERVERS.COM
Name Server: DNS2.REGISTRAR-SERVERS.COM
DNSSEC: unsigned
Registry Billing ID: C153667773-CNIC
Billing Name: WhoisGuard Protected
Billing Organization: WhoisGuard, Inc.
Billing Street: P.O. Box 0823-03411
Billing City: Panama
Billing State/Province: Panama
Billing Postal Code:
Billing Country: PA
Billing Phone: +507.8365503
Billing Fax: +51.17057182
Billing Email: fa2174061cfe420dbee5a89e29053d94.protect@whoisguard.com
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2017-10-15T23:07:00.0Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

This whois service is provided by CentralNic Ltd and only contains
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd https://www.centralnic.com/

Access to the whois service is rate limited. For more information, please
see https://registrar-console.centralnic.com/pub/whois_guidance.
</details>
(Sorry for missing line breaks: no matter what I do, they show up on "Write" tab, but not on "Preview" tab.)

### About other TLDs
Also, there might be some other TLDs that are not supported, complete list of all currently registered TLDs can be obtained from IANA [here](https://www.icann.org/resources/pages/tlds-2012-02-25-en) (updated regularly). From what I (know)[https://www.iana.org/domains/reserved], `example.tld` is registered by IANA in all open TLDs. Therefore, it should be pretty simple to request whois for `example.tld` for all TLDs in the list and then see which fail and with what error. Unfortunately, I don't have time for this right now, but I might do it later and submit a PR, if you are interested.

**Comment by hjr265** [comment]
@bershan2 Thanks! This is now done.

**Comment by spieglio** [comment]
@hjr265 Are you considering to add the host of other domains that are currently not supported? Should that be a different GH issue?

**Comment by hjr265** [comment]
@spieglio That would be nice!

You can request multiple additions through an issue. What would help a lot to get this done super fast is if you mentioned the WHOIS server addresses as well for each domain in the request.
