### ISSUE TITLE
the option timeout is does not take effect

### ISSUE THREAD

**Issue by superwunc** [FurqanSoftware/node-whois#52]
I found setting the timeout option and did not take effect。
net.createConnection(options[, connectListener])
timeout <number> If set, will be used to call socket.setTimeout(timeout) after the socket is created, but before it starts the connection.

socket.setTimeout(3000);
socket.on('timeout', () => {
  console.log('socket timeout');
  socket.end();
});

**Comment by kcwinner** [comment]
Added a PR for this

**Comment by kcwinner** [comment]
This can be marked as closed.
