### ISSUE TITLE
Recursive whois broken on verisign whois

### ISSUE THREAD

**Issue by devl00p** [FurqanSoftware/node-whois#53]
Hello,

Verisign changed the format of their whois responses.

Whois server address given in Verisign responses in now prefixed with "Registrar WHOIS Server:"

The regex in the node-whois code isn't up-to-date (currently: (ReferralServer|Registrar Whois|Whois Server|WHOIS Server)) so extracting the server address doesn't work and resolution stop early.

**Comment by hjr265** [comment]
@devl00p The regular expression for this has been updated in the latest version.
