### ISSUE TITLE
Issues with Latin characters

### ISSUE THREAD

**Issue by zbone3** [FurqanSoftware/node-whois#60]
In several of cases when I query IPs/domains that belong to an organization with a name that contains accented Latin characters, these characters are not encoded properly.
I know the package uses utf-8 as the default encoding, but for some reason this issue only happens with accented Latin characters.

`Example IP: 148.241.109.161`

**Expected output:** Instituto Tecnológico y de Estudios Superiores de Monterrey

**Received output:** Instituto Tecnol�gico y de Estudios Superiores de Monterrey

When I hardcode `socket.setEncoding('binary') ` to your lib it actually fixes this issue, but then other unicode languages such as Chinese are not displayed correctly. 

Is it possible to fix it? Or maybe even add an 'encoding' option, so I can pass a specific encoding in case the results contains unexpected characters. 

Thanks

**Comment by hjr265** [comment]
You can now pass the encoding in the options object:

```
whois.lookup('148.241.109.161', {encoding: 'binary'}, callback);
```

**Comment by umutm** [comment]
I have been playing with the encoding options and, whichever option I tried, I couldn't successfully encode this request:
`whois.lookup('yahoo.com.tr', {encoding: 'binary'}, callback);`

Tried utf8, latin1 and others as well.

Any feedback on how to get it successfully encoded? Thanks very much.
