### ISSUE TITLE
RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536

### ISSUE THREAD

**Issue by AdamSlack** [FurqanSoftware/node-whois#65]
When doing a lookup for `theaternetz.org`
```js
whois.lookup('theaternetz.org', function(err, data) {
  console.log(data)
})
```

The Following Error is given.
```
Socket {
  connecting: true,
  _hadError: false,
  _handle:
   TCP {
     reading: false,
     owner: [Circular],
     onread: [Function: onread],
     onconnection: null,
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] } },
  _parent: null,
  _host: 'whois.pir.org',
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: true,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] },
  _events:
   { end: [Function: onReadableStreamEnd],
     connect:
      { [Function: bound onceWrapper] listener: [Function: connect] },
     data: [Function],
     timeout: [Function],
     error: [Function],
     close: [Function] },
  _eventsCount: 6,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 17,
     writing: true,
     corked: 0,
     sync: false,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: [Function: nop],
     writelen: 17,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 1,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: 'theaternetz.org\r\n',
  _pendingEncoding: 'utf8',
  server: null,
  _server: null,
  [Symbol(asyncId)]: 159,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]:
   Timeout {
     _called: false,
     _idleTimeout: 60000,
     _idlePrev:
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _unrefed: true,
        msecs: 60000,
        _timer: [Timer] },
     _idleNext:
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _unrefed: true,
        msecs: 60000,
        _timer: [Timer] },
     _idleStart: 3064,
     _onTimeout: [Function: bound ],
     _timerArgs: undefined,
     _repeat: null,
     _destroyed: false,
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] },
     [Symbol(unrefed)]: true,
     [Symbol(asyncId)]: 162,
     [Symbol(triggerId)]: 5 },
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }


RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received //isp.cronon.net/whois-abfrage/.
    at lookupAndConnect (net.js:1010:13)
    at Socket.connect (net.js:986:5)
    at Object.connect (net.js:152:35)
    at Object.lookup (/home/hapax/github/XRayTrackerMapper/node_modules/whois/index.js:160:22)
``

**Comment by AdamSlack** [comment]
Same issue as #64, gonna close :)

**Comment by samohan123** [comment]
It might be coz the **localhost** is not defined with the *required syntax* in the **"hosts"** file of the system.
The file can be located @:

=>            etc/hosts
(above file for ***linux***)
or
=>            c:\ **Windows** \System32\Drivers\ **etc** \ **hosts**
(above file for **Windows**)

i.e. file has some wrong input.

So, Try replacing everything in that file with the text below as this is the default text that was always there in *hosts* file when it worked fine:


127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
fe80::1%lo0	localhost

**Comment by jithinjosejacob** [comment]
For mine,same issue happened when i didnt specified the port number for selenium in the conf file,once i defined 4444 there,it picked the port as 4444 in webdriverio and started running the tests without above issue

**Comment by billdiab** [comment]
> For mine,same issue happened when i didnt specified the port number for selenium in the conf file,once i defined 4444 there,it picked the port as 4444 in webdriverio and started running the tests without above issue

Would you mind sharing the location of the config file and the exact piece of code you added?
Thanks

**Comment by jithinjosejacob** [comment]
--My config file,i added line 10 port:4444 to the same--

exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',
    port: 4444,
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        './test/**/*.js'
    ],
    // Patterns to exclude.
    //exclude: [
        // 'path/to/excluded/files'
    //],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'error',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner, @wdio/lambda-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/applitools-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'my url',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['chromedriver'],
    
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter.html
    //reporters: ['spec','dot'],
 
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialised
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
     beforeTest: function () {
         const chai = require('chai')
         const chaiWebdriver = require('chai-webdriverio').default

         chai.use(chaiWebdriver(browser))
         global.assert = chai.assert
         global.should = chai.should
         global.expect = chai.expect
     },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine).
     */
    // afterTest: function(test, context, { error, result, duration, passed, retries }) {
    // },


    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    //onReload: function(oldSessionId, newSessionId) {
    //}
}

**Comment by billdiab** [comment]
> --My config file,i added line 10 port:4444 to the same--
> 
> exports.config = {
> //
> // ====================
> // Runner Configuration
> // ====================
> //
> // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
> // on a remote machine).
> runner: 'local',
> port: 4444,
> //
> // ==================
> // Specify Test Files
> // ==================
> // Define which test specs should run. The pattern is relative to the directory
> // from which `wdio` was called. Notice that, if you are calling `wdio` from an
> // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
> // directory is where your package.json resides, so `wdio` will be called from there.
> //
> specs: [
> './test/**/*.js'
> ],
> // Patterns to exclude.
> //exclude: [
> // 'path/to/excluded/files'
> //],
> //
> // ============
> // Capabilities
> // ============
> // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
> // time. Depending on the number of capabilities, WebdriverIO launches several test
> // sessions. Within your capabilities you can overwrite the spec and exclude options in
> // order to group specific specs to a specific capability.
> //
> // First, you can define how many instances should be started at the same time. Let's
> // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
> // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
> // files and you set maxInstances to 10, all spec files will get tested at the same time
> // and 30 processes will get spawned. The property handles how many capabilities
> // from the same test should run tests.
> //
> maxInstances: 10,
> //
> // If you have trouble getting all important capabilities together, check out the
> // Sauce Labs platform configurator - a great tool to configure your capabilities:
> // https://docs.saucelabs.com/reference/platforms-configurator
> //
> capabilities: [{
> 
> ```
>     // maxInstances can get overwritten per capability. So if you have an in-house Selenium
>     // grid with only 5 firefox instances available you can make sure that not more than
>     // 5 instances get started at a time.
>     maxInstances: 5,
>     //
>     browserName: 'chrome',
>     // If outputDir is provided WebdriverIO can capture driver session logs
>     // it is possible to configure which logTypes to include/exclude.
>     // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
>     // excludeDriverLogs: ['bugreport', 'server'],
> }],
> //
> // ===================
> // Test Configurations
> // ===================
> // Define all options that are relevant for the WebdriverIO instance here
> //
> // Level of logging verbosity: trace | debug | info | warn | error | silent
> logLevel: 'error',
> //
> // Set specific log levels per logger
> // loggers:
> // - webdriver, webdriverio
> // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
> // - @wdio/mocha-framework, @wdio/jasmine-framework
> // - @wdio/local-runner, @wdio/lambda-runner
> // - @wdio/sumologic-reporter
> // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
> // Level of logging verbosity: trace | debug | info | warn | error | silent
> // logLevels: {
> //     webdriver: 'info',
> //     '@wdio/applitools-service': 'info'
> // },
> //
> // If you only want to run your tests until a specific amount of tests have failed use
> // bail (default is 0 - don't bail, run all tests).
> bail: 0,
> //
> // Set a base URL in order to shorten url command calls. If your `url` parameter starts
> // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
> // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
> // gets prepended directly.
> baseUrl: 'my url',
> //
> // Default timeout for all waitFor* commands.
> waitforTimeout: 10000,
> //
> // Default timeout in milliseconds for request
> // if browser driver or grid doesn't send response
> connectionRetryTimeout: 90000,
> //
> // Default request retries count
> connectionRetryCount: 3,
> //
> // Test runner services
> // Services take over a specific job you don't want to take care of. They enhance
> // your test setup with almost no effort. Unlike plugins, they don't add new
> // commands. Instead, they hook themselves up into the test process.
> services: ['chromedriver'],
> 
> // Framework you want to run your specs with.
> // The following are supported: Mocha, Jasmine, and Cucumber
> // see also: https://webdriver.io/docs/frameworks.html
> //
> // Make sure you have the wdio adapter package for the specific framework installed
> // before running any tests.
> framework: 'mocha',
> //
> // The number of times to retry the entire specfile when it fails as a whole
> // specFileRetries: 1,
> //
> // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
> // specFileRetriesDeferred: false,
> //
> // Test reporter for stdout.
> // The only one supported by default is 'dot'
> // see also: https://webdriver.io/docs/dot-reporter.html
> //reporters: ['spec','dot'],
> 
> //
> // Options to be passed to Mocha.
> // See the full list at http://mochajs.org/
> mochaOpts: {
>     ui: 'bdd',
>     timeout: 60000
> },
> //
> // =====
> // Hooks
> // =====
> // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
> // it and to build services around it. You can either apply a single function or an array of
> // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
> // resolved to continue.
> /**
>  * Gets executed once before all workers get launched.
>  * @param {Object} config wdio configuration object
>  * @param {Array.<Object>} capabilities list of capabilities details
>  */
> // onPrepare: function (config, capabilities) {
> // },
> /**
>  * Gets executed before a worker process is spawned and can be used to initialise specific service
>  * for that worker as well as modify runtime environments in an async fashion.
>  * @param  {String} cid      capability id (e.g 0-0)
>  * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
>  * @param  {[type]} specs    specs to be run in the worker process
>  * @param  {[type]} args     object that will be merged with the main configuration once worker is initialised
>  * @param  {[type]} execArgv list of string arguments passed to the worker process
>  */
> // onWorkerStart: function (cid, caps, specs, args, execArgv) {
> // },
> /**
>  * Gets executed just before initialising the webdriver session and test framework. It allows you
>  * to manipulate configurations depending on the capability or spec.
>  * @param {Object} config wdio configuration object
>  * @param {Array.<Object>} capabilities list of capabilities details
>  * @param {Array.<String>} specs List of spec file paths that are to be run
>  */
> // beforeSession: function (config, capabilities, specs) {
> // },
> /**
>  * Gets executed before test execution begins. At this point you can access to all global
>  * variables like `browser`. It is the perfect place to define custom commands.
>  * @param {Array.<Object>} capabilities list of capabilities details
>  * @param {Array.<String>} specs List of spec file paths that are to be run
>  */
> // before: function (capabilities, specs) {
> // },
> /**
>  * Runs before a WebdriverIO command gets executed.
>  * @param {String} commandName hook command name
>  * @param {Array} args arguments that command would receive
>  */
> // beforeCommand: function (commandName, args) {
> // },
> /**
>  * Hook that gets executed before the suite starts
>  * @param {Object} suite suite details
>  */
> // beforeSuite: function (suite) {
> // },
> /**
>  * Function to be executed before a test (in Mocha/Jasmine) starts.
>  */
>  beforeTest: function () {
>      const chai = require('chai')
>      const chaiWebdriver = require('chai-webdriverio').default
> 
>      chai.use(chaiWebdriver(browser))
>      global.assert = chai.assert
>      global.should = chai.should
>      global.expect = chai.expect
>  },
> /**
>  * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
>  * beforeEach in Mocha)
>  */
> // beforeHook: function (test, context) {
> // },
> /**
>  * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
>  * afterEach in Mocha)
>  */
> // afterHook: function (test, context, { error, result, duration, passed, retries }) {
> // },
> /**
>  * Function to be executed after a test (in Mocha/Jasmine).
>  */
> // afterTest: function(test, context, { error, result, duration, passed, retries }) {
> // },
> 
> 
> /**
>  * Hook that gets executed after the suite has ended
>  * @param {Object} suite suite details
>  */
> // afterSuite: function (suite) {
> // },
> /**
>  * Runs after a WebdriverIO command gets executed
>  * @param {String} commandName hook command name
>  * @param {Array} args arguments that command would receive
>  * @param {Number} result 0 - command success, 1 - command error
>  * @param {Object} error error object if any
>  */
> // afterCommand: function (commandName, args, result, error) {
> // },
> /**
>  * Gets executed after all tests are done. You still have access to all global variables from
>  * the test.
>  * @param {Number} result 0 - test pass, 1 - test fail
>  * @param {Array.<Object>} capabilities list of capabilities details
>  * @param {Array.<String>} specs List of spec file paths that ran
>  */
> // after: function (result, capabilities, specs) {
> // },
> /**
>  * Gets executed right after terminating the webdriver session.
>  * @param {Object} config wdio configuration object
>  * @param {Array.<Object>} capabilities list of capabilities details
>  * @param {Array.<String>} specs List of spec file paths that ran
>  */
> // afterSession: function (config, capabilities, specs) {
> // },
> /**
>  * Gets executed after all workers got shut down and the process is about to exit. An error
>  * thrown in the onComplete hook will result in the test run failing.
>  * @param {Object} exitCode 0 - success, 1 - fail
>  * @param {Object} config wdio configuration object
>  * @param {Array.<Object>} capabilities list of capabilities details
>  * @param {<Object>} results object containing test results
>  */
> // onComplete: function(exitCode, config, capabilities, results) {
> // },
> /**
> * Gets executed when a refresh happens.
> * @param {String} oldSessionId session ID of the old session
> * @param {String} newSessionId session ID of the new session
> */
> //onReload: function(oldSessionId, newSessionId) {
> //}
> ```
> 
> }

Thank you!!!
