### ISSUE TITLE
No whois data for spiderdream.in.net

### ISSUE THREAD

**Issue by zeichee** [FurqanSoftware/node-whois#70]
I am not getting the expected whois data for spiderdream.in.net when using the whois package, but when I tried to use the whois command in my local machine, it gives the whois data
![2](https://user-images.githubusercontent.com/10136536/49560013-cd7a2e00-f94b-11e8-9cea-c431cbfa4c02.PNG)
![1](https://user-images.githubusercontent.com/10136536/49560151-3e214a80-f94c-11e8-95f1-8694af79b8b8.PNG)

**Comment by hjr265** [comment]
@zeichee This is because the CLI has the `follow` option set to 0 by default. But, the when queried through the libraries API, the `follow` option is set to 2.

The WHOIS lookup fails when the library tries to follow to the next whois server whois.PublicDomainRegistry.com.

**Comment by zeichee** [comment]
does this mean it's not a bug?

**Comment by hjr265** [comment]
It's likely an issue with whois.PublicDomainRegistry.com.
