### ISSUE TITLE
README.md: change proxy.ipaddress --> proxy.host

### ISSUE THREAD

**Issue by whocares666666** [FurqanSoftware/node-whois#77]
In the "Usage" options section, proxy.ipaddress should be proxy.host to work with the latest ```socks@2.3.1``` module:

```
	"proxy": {       // (optional) SOCKS Proxy
		"host": "",
```

**Comment by moneals** [comment]
I gave up waiting on a fix and don't do coffeescript so I created a javascript version here: https://github.com/moneals/whois-raw
